name: Commit Checks

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Mark as executable
      run: chmod +x gradlew
    - name: Build jar
      run: ./gradlew desktop:dist
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: desktop/build/libs/${{ github.event.repository.name }}-1.0.jar